server:
  port: 8761
  
spring:
  application:
    name: SERVICE-REGISTRY
  
eureka:
  client:
    register-with-eureka: false   

#/home/coder/project/workspace/serviceregistry/target/serviceregistry-0.0.1-SNAPSHOT.jar