server:
  port: 8082
  
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/isp
    username: root
    password: examly
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: STORY-MANAGEMENT-API